version: '3.3'
services:
  docker-mariadb:
    image: mariadb
    container_name: mariadb_crud
    ports:
    - "3306:3306"
    volumes:
    - ./db/:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=testdb
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password