version: '3.3'
services:
  database:
    image: mysql
    ports:
    - "${ENV_DATABASE_PORTS}"
    volumes:
    - ./db/:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_ROOT_PASSWORD=${ENV_DATABASE_ROOT_PASSWORD}
    - MYSQL_DATABASE=${ENV_DATABASE_DATABASE}
    - MYSQL_USER=${ENV_DATABASE_APPLICATION_USER}
    - MYSQL_PASSWORD=${ENV_DATABASE_APPLICATION_PASSWORD}
  web:
    image: nginx
    ports:
    - "8080:80"
    build:
      context: $PWD/nginx
    command: [nginx-debug, '-g', 'daemon off;']
    links:
    - calculator
    - calculator2
    depends_on:
    - calculator
    - calculator2
  calculator:
    build:
      context: $PWD/app
      args:
      - server_port=${ENV_APPLICATION_PORT}
      - server=${ENV_APPLICATION_SERVER}
    ports:
    - "${ENV_APPLICATION_PORTS}"
    deploy:
      mode: replicated
      replicas: 2
    environment:
    - SERVER_PORT=${ENV_APPLICATION_PORT}
    - MY_DATABASE_SERVER=${ENV_DATABASE_SERVER}
    - MY_DATABASE_DATABASE=${ENV_DATABASE_DATABASE}
    - MY_DATABASE_PORT=${ENV_DATABASE_PORT}
    - MY_DATABASE_USER=${ENV_DATABASE_APPLICATION_USER}
    - MY_DATABASE_PASSWORD=${ENV_DATABASE_APPLICATION_PASSWORD}
    depends_on:
    - ${ENV_DATABASE_SERVER}
  calculator2:
    build:
      context: $PWD/app
      args:
      - server_port=${ENV_APPLICATION_PORT_2}
      - server=${ENV_APPLICATION_SERVER_2}
    ports:
    - "${ENV_APPLICATION_PORTS_2}"
    environment:
    - SERVER_PORT=${ENV_APPLICATION_PORT_2}
    - MY_DATABASE_SERVER=${ENV_DATABASE_SERVER}
    - MY_DATABASE_DATABASE=${ENV_DATABASE_DATABASE}
    - MY_DATABASE_PORT=${ENV_DATABASE_PORT}
    - MY_DATABASE_USER=${ENV_DATABASE_APPLICATION_USER}
    - MY_DATABASE_PASSWORD=${ENV_DATABASE_APPLICATION_PASSWORD}
    depends_on:
    - ${ENV_DATABASE_SERVER}

  prometheus:
    image: prom/prometheus
    ports:
    - "${ENV_COLLECTOR_PORTS}"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
    - ${ENV_APPLICATION_SERVER}
    - ${ENV_APPLICATION_SERVER_2}
  grafana:
    image: grafana/grafana
    ports:
    - ${ENV_MONITOR_PORTS}
    volumes:
    - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasources.yml
    depends_on:
    - ${ENV_COLLECTOR_SERVER}