version: '3.3'
services:
  database:
    build:
      context: $PWD/mysql
#    image: mysql
    restart: always
    ports:
    - "${ENV_DATABASE_PORTS}"
    volumes:
    - ./mysql/scripts/:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_ROOT_PASSWORD=${ENV_DATABASE_ROOT_PASSWORD}
    - MYSQL_DATABASE=${ENV_DATABASE_DATABASE}
    - MYSQL_USER=${ENV_DATABASE_APPLICATION_USER}
    - MYSQL_PASSWORD=${ENV_DATABASE_APPLICATION_PASSWORD}
  database-exporter:
    build:
      context: $PWD/mysql-exporter
    restart: always
    ports:
    - "9104:9104"
    environment:
    - DATA_SOURCE_NAME=exporter:password@(database:3306)/performance_schema
    depends_on:
    - database
  web:
    image: nginx
    restart: always
    ports:
    - "8080:80"
    build:
      context: $PWD/nginx
    command: [nginx-debug, '-g', 'daemon off;']
    links:
    - calculator
    - calculator2
    depends_on:
    - calculator
    - calculator2
  calculator:
    build:
      context: $PWD/app
      args:
      - server_port=${ENV_APPLICATION_PORT}
      - server=${ENV_APPLICATION_SERVER}
    restart: always
    ports:
    - "${ENV_APPLICATION_PORTS}"
    environment:
    - SERVER_PORT=${ENV_APPLICATION_PORT}
    - MY_DATABASE_SERVER=${ENV_DATABASE_SERVER}
    - MY_DATABASE_DATABASE=${ENV_DATABASE_DATABASE}
    - MY_DATABASE_PORT=${ENV_DATABASE_PORT}
    - MY_DATABASE_USER=${ENV_DATABASE_APPLICATION_USER}
    - MY_DATABASE_PASSWORD=${ENV_DATABASE_APPLICATION_PASSWORD}
    depends_on:
    - ${ENV_DATABASE_SERVER}
  calculator2:
    build:
      context: $PWD/app
      args:
      - server_port=${ENV_APPLICATION_PORT_2}
      - server=${ENV_APPLICATION_SERVER_2}
    restart: always
    ports:
    - "${ENV_APPLICATION_PORTS_2}"
    environment:
    - SERVER_PORT=${ENV_APPLICATION_PORT_2}
    - MY_DATABASE_SERVER=${ENV_DATABASE_SERVER}
    - MY_DATABASE_DATABASE=${ENV_DATABASE_DATABASE}
    - MY_DATABASE_PORT=${ENV_DATABASE_PORT}
    - MY_DATABASE_USER=${ENV_DATABASE_APPLICATION_USER}
    - MY_DATABASE_PASSWORD=${ENV_DATABASE_APPLICATION_PASSWORD}
    depends_on:
    - ${ENV_DATABASE_SERVER}
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
    - "${ENV_COLLECTOR_PORTS}"
    volumes:
    - ./resources/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
    - ${ENV_APPLICATION_SERVER}
    - ${ENV_APPLICATION_SERVER_2}
  grafana:
    image: grafana/grafana
    restart: always
    ports:
    - ${ENV_MONITOR_PORTS}
    volumes:
    - ./resources/grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasources.yml
    depends_on:
    - ${ENV_COLLECTOR_SERVER}