version: '3.3'
services:
  database:
    build:
      context: $PWD/mysql
    restart: always
    ports:
    - "3306:3306"
    volumes:
    - ./mysql/scripts/:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_ROOT_PASSWORD=${ENV_DATABASE_ROOT_PASSWORD}
    - MYSQL_DATABASE=${ENV_DATABASE_DATABASE}
    - MYSQL_USER=${ENV_DATABASE_APPLICATION_USER}
    - MYSQL_PASSWORD=${ENV_DATABASE_APPLICATION_PASSWORD}
  database-exporter:
    build:
      context: $PWD/mysql-exporter
    restart: always
    ports:
    - "9104:9104"
    environment:
    - DATA_SOURCE_NAME=exporter:password@(database:3306)/performance_schema
    depends_on:
    - database
  web:
    image: nginx
    restart: always
    ports:
    - "8080:80"
    build:
      context: $PWD/nginx
    command: [nginx-debug, '-g', 'daemon off;']
    links:
    - calculator
    - calculator2
    depends_on:
    - calculator
    - calculator2
  calculator:
    build:
      context: $PWD/app
    restart: always
    ports:
    - "8091:8091"
    environment:
    - SERVER_PORT=8091
    - MY_DATABASE_SERVER=database
    - MY_DATABASE_PORT=${ENV_DATABASE_PORT}
    - MY_DATABASE_DATABASE=${ENV_DATABASE_DATABASE}
    - MY_DATABASE_USER=${ENV_DATABASE_APPLICATION_USER}
    - MY_DATABASE_PASSWORD=${ENV_DATABASE_APPLICATION_PASSWORD}
    depends_on:
    - database
    healthcheck:
      test: curl -f http://calculator:8091/actuator/health || exit 1
      interval: 1m
      timeout: 2s
      retries: 5
  calculator2:
    build:
      context: $PWD/app
    restart: always
    ports:
    - "8092:8092"
    environment:
    - SERVER_PORT=8092
    - MY_DATABASE_SERVER=database
    - MY_DATABASE_PORT=${ENV_DATABASE_PORT}
    - MY_DATABASE_DATABASE=${ENV_DATABASE_DATABASE}
    - MY_DATABASE_USER=${ENV_DATABASE_APPLICATION_USER}
    - MY_DATABASE_PASSWORD=${ENV_DATABASE_APPLICATION_PASSWORD}
    depends_on:
    - database
    healthcheck:
      test: curl -f http://calculator2:8092/actuator/health || exit 1
      interval: 1m
      timeout: 2s
      retries: 5
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
    - "9090:9090"
    volumes:
    - ./resources/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
    - calculator
    - calculator2
    - database-exporter
  grafana:
    image: grafana/grafana
    restart: always
    ports:
    - "3000:3000"
    volumes:
    - ./resources/grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasources.yml
    depends_on:
    - prometheus